name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: make install

      - name: Run unit tests
        run: make test

      - name: Start application
        run: |
          make start &
          sleep 5

      - name: Check k6 files
        run: |
          pwd
          ls -la
          ls -la scripts

      - name: Run k6 performance tests
        id: k6_test
        continue-on-error: true
        env:
          K6_HOST: ${{ secrets.K6_HOST }}
          PORT: ${{ secrets.PORT }}
          K6_VUS: ${{ secrets.K6_VUS }}
          K6_DURATION: ${{ secrets.K6_DURATION }}
        run: make k6

      - name: Performance test failed
        if: steps.k6_test.outcome == 'failure'
        run: |
          echo "Not good and it will not be deploy"
          exit 1

      - name: Deploy
        if: steps.k6_test.outcome == 'success'
        run: echo "Good and it will be deploy"
